Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways 
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray** 



In [ ]:
import numpy as np
import pandas as pd
import math as mt

In [ ]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it 
arr = np.array([1,2,3,4,5])
print(arr)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it 
arr1 = np.zeros((3,3))
print(arr1)

[1 2 3 4 5]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]
def createArr():
  ar = np.random.randn(3,4)
  print(ar)
createArr()
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
def createArrZeros():
  ar = np.zeros((3,4))
  print(ar)
createArrZeros()

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
def createArrOnes():
  ar = np.ones((3,4))
  print(ar)
createArrOnes()


[[ 1.58720899  0.50435244 -0.34278608  0.26528953]
 [-0.00585603  0.85257458 -0.67131744  1.20117451]
 [-1.20596305  0.2682673  -0.72521877 -0.4635882 ]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
def arr():
  a = np.linspace(1,20,10)
  print(a)
arr()

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


### Basic array operations
- algebraic operations 
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
def add_Arr():
  arr = np.add(a,b)
  print(arr)
  arr = np.subtract(a,b)
  print(arr)
  arr = np.multiply(a,b)
  print(arr)
  arr = np.divide(a,b)
  print(arr)
add_Arr()

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0 
def add_Arr_x():
  arr = np.sum(a,axis=0)
  print(arr)  
add_Arr_x()
# Write a NumPy function to get the sum of the array 'a' along axis=1 
def add_Arr_y():
  arr = np.sum(a,axis = 1)
  print(arr)  
add_Arr_y()

[ 6 17 14]
[10 13 14]


In [ ]:
# Write a NumPy function to reverse the array 'a' 
def reverse_func():
  rev = np.flip(a)
  print(rev)
reverse_func()

# Write a NumPy function to reverse the array 'a' along axis=0
def reverse_func0():
  rev = np.flip(a,axis = 0)
  print(rev)
reverse_func0()

# Write a NumPy function to reverse the array 'a' along axis=1
def reverse_func1():
  rev = np.flip(a,axis = 1)
  print(rev)
reverse_func1()

[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a' 
def sort_arr():
  c = np.sort(a)
  print(c)
sort_arr()
# Write a NumPy function to sort the array 'a' along axis=0
def sort_arr0():
  c = np.sort(a,axis = 0)
  print(c)
sort_arr0()
# Write a NumPy function to sort the array 'a' along axis=1
def sort_arr1():
  c = np.sort(a,axis = 1)
  print(c)
sort_arr1()
# Write a NumPy function to sort the array 'a' in descending order along axis=0
def sort_arr3():
  c = np.sort(a,axis = 0)
  c = np.flip(b,axis = 0)
  print(c)
sort_arr3()

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[61 48 75]
 [90 37 81]
 [11 16 18]]


In [ ]:
# Write a NumPy function to argsort the array along axis=0
def arg_sort():
  c = np.argsort(a,kind = 'quicksort', axis = 0)
  print(c)
arg_sort()

# Write a NumPy function to argsort the array along axis=1
def arg_sort1():
  c = np.argsort(a,kind ='quicksort', axis = 1)
  print(c)
arg_sort1()

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
def concat():
  c = np.concatenate((a,b))
  print(c)
concat()

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
def concat1():
  c = np.concatenate((a,b),axis = 0)
  print(c)
concat1()

# Note: You can do the same function using stacking, discover and try that :)


[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
def dimen():
  n = np.ndim(a)
  print(n)
dimen()

# Write a NumPy function to get the Shape of the array  
def shape_arr():
  n = np.shape(a)
  print(n)
shape_arr()

# Write a NumPy function to get the Size of the array
def size_arr():
  n = np.size(a)
  print(n)
size_arr()

2
(3, 3)
9


In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
def reshape_arr():
  c = a.reshape(1,9)
  return c
print(reshape_arr())


[[4 6 8 9 3 1 1 8 5]]


In [ ]:
# Write a NumPy function to add a new axis to the array 'a' 

# Note : Show atleast two different ways of doing this 

def new_axis():
  y = np.expand_dims(a, axis = 1)
  print(y)
  y = a[:,np.newaxis ]
  print(y)
new_axis()




[[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]]
[[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range


In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4 
lst=[]
for i in range(3):
  for j in range(3):
    if a[i][j]>4:
      lst.append(a[i][j])
print(lst)

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
lst=[]
for i in range(3):
  for j in range(3):
    if a[i][j]>4 and a[i][j]%2==0:
      lst.append(a[i][j])
print(lst)

[6, 8, 5]
[6, 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
def cop():
  b = np.copy(a)
  print(b+1)
cop()

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset 

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [ ]:
# Write a Pandas function to drop rows that contain a missing value. 

def drop_row(): 
  iris_data = pd.DataFrame(iris_2d) 
  iris_data.dropna(inplace=True)

drop_row()

In [ ]:
# Write a Pandas function to find the correlation between the first two columns.
def col():
  iris_data = pd.DataFrame(iris_2d)
  print(round(iris_data[0].corr(iris_data[1]),4))
col()


-0.1094


In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
iris_data = pd.DataFrame(iris_2d)
m1 = iris_data[2].mean()
m2 = iris_data[2].median()
m3 = iris_data[2].std()
print('The mean of column 3 is ', round(m1,2) )
print('The median of column 3 is ', m2)
print('The standard deviation of column 3 is ', round(m3,2))


The mean of column 3 is  3.76
The median of column 3 is  4.35
The standard deviation of column 3 is  1.76


In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints: 
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
arr = np.ones((150,1))
df = pd.DataFrame(iris_2d)
print(df.head())
lst = []
for i in range(150):
  lst.append((mt.pi* iris_2d[i][2] * iris_2d[i][0] * iris_2d[i][0])/3)
df.insert(4, 'Volume', lst)
print(df.head())



     0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2
     0    1    2    3     Volume
0  5.1  3.5  1.4  0.2  38.132652
1  4.9  3.0  1.4  0.2  35.200498
2  4.7  3.2  1.3  0.2  30.072372
3  4.6  3.1  1.5  0.2  33.238050
4  5.0  3.6  1.4  0.2  36.651914


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
x = np.arange(4, dtype=np.int64)
a = np.ones(np.shape(x), dtype = np.int64)
print(a)

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
s1 = x[:4]
s2 = x[4:7]
s3 = x[6:]
print(s1)
print(s2)
print(s3)

[1 2 3 4]
[5 6 7]
[7 8 9]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
x = np.random.uniform(0, 10, (2,5))
print(x)
for i in range(5):
  max = x[0][i]
  max_r = 0 
  max_c = i 
  for j in range(2):
    if x[j][i]>max:
      max = x[j][i]
      max_r = j
      max_c = i
  print("The max value in column ",i+1, "is ", max," and its index is ", max_r+1,', ',max_c+1)




[[4.02421547e+00 3.19794983e+00 8.82600509e+00 3.43394440e+00
  8.43605065e+00]
 [5.34040820e-01 7.02644503e+00 4.82968882e-03 9.61758905e+00
  4.96202484e+00]]
The max value in column  1 is  4.024215473721019  and its index is  1 ,  1
The max value in column  2 is  7.026445029987616  and its index is  2 ,  2
The max value in column  3 is  8.826005093427968  and its index is  1 ,  3
The max value in column  4 is  9.617589046338242  and its index is  2 ,  4
The max value in column  5 is  8.436050652485127  and its index is  1 ,  5


### Pandas

Run the following load command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [ ]:
def count_sp():
  df = pd.DataFrame(iris)
  df = df.set_axis(names, axis=1)
  n = len(pd.unique(df['species']))
  print("No of unique species " ,n)
count_sp()





No of unique species  3


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# If the dtype was object the elements were byte strings

def bin_func():
  lst  = []
  for i in range(150):
    if iris[i][2] < 3:
      lst.append('small')
    if iris[i][2] >= 3 and int(iris[i][2]) < 5  :
      lst.append('medium')
    if iris[i][2] >= 5:
      lst.append('large')
  print(lst)
bin_func()



['small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'large', 'large', 'large', 'large', 'large

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

def freq():
  df = pd.DataFrame(iris)
  df = df.set_axis(names, axis=1)
  ar = df.mode()
  print(ar['petallength'][0])
freq()


1.5
