Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways 
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray** 



In [84]:
import numpy as np

In [85]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it 
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [86]:
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it 
arr_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [87]:
# Write a NumPy function to create an array with random values of shape [3,4]
arr=np.random.rand(3,4)

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
arr0=np.zeros((3,4))

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
arr1=np.ones((3,4))

In [88]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
arr=np.arange(1,10,2) # this will create an array with start point 1,end point 10,and difference of 2 between every element.

### Basic array operations
- algebraic operations 
- logical operations

In [89]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [90]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b

c=a+b #addition
d=a-b #subtraction
e=np.matmul(a,b) #matrix multiplication
f=np.divide(a,b) #division

In [91]:
# Write a NumPy function to get the sum of the array 'a' along axis=0 
sum0=np.sum(a,axis=0)
# Write a NumPy function to get the sum of the array 'a' along axis=1 
sum1=np.sum(a,axis=1)

In [92]:
# Write a NumPy function to reverse the array 'a' 
b=np.flip(a)
# Write a NumPy function to reverse the array 'a' along axis=0
c=np.flip(a,axis=0)
# Write a NumPy function to reverse the array 'a' along axis=1
d=np.flip(a,axis=1)

### Sorting and concatenation
- sort arrays
- join multiple arrays


In [93]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [94]:
# Write a NumPy function to sort the array 'a' 
c=np.sort(a)

# Write a NumPy function to sort the array 'a' along axis=0
d=np.sort(a,axis=0)

# Write a NumPy function to sort the array 'a' along axis=1
e=np.sort(a,axis=1)

# Write a NumPy function to sort the array 'a' in descending order along axis=0
f=-np.sort(-a,axis=0)

In [95]:
# Write a NumPy function to argsort the array along axis=0
c=np.argsort(a,axis=0)

# Write a NumPy function to argsort the array along axis=1
d=np.argsort(a,axis=1)

In [96]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
c=np.concatenate((a,b),axis=None)

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
d=np.concatenate((a,b),axis=0)

# Note: You can do the same function using stacking, discover and try that :)
e=np.stack((a,b)) #numpy.org :)


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [97]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [98]:
# Write a NumPy function to get the Number of dimensions
print(a.ndim)

# Write a NumPy function to get the Shape of the array  
print(a.shape)

# Write a NumPy function to get the Size of the array
print(a.size)


2
(3, 3)
9


In [99]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
newarr= a.reshape(1,9)
print(newarr)

[[4 6 8 9 3 1 1 8 5]]


In [100]:
# Write a NumPy function to add a new axis to the array 'a' 
# Note : Show atleast two different ways of doing this 

#1st way
a=np.expand_dims(a,axis=0)

#2nd way
b=a[np.newaxis,:] 

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [101]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [102]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range


In [103]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4 
b=a[a>4]
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
c=a[(a>4)&(a%2==0)]

### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [104]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [105]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
b=a.copy()
b+=1
print(b)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset 

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [106]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [107]:
import pandas as pd
# Write a Pandas function to drop rows that contain a missing value. 
df=pd.DataFrame(iris_2d)
df.dropna(axis=0)


0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [108]:
# Write a Pandas function to find the correlation between the first two columns.
df=pd.DataFrame({
'c1':iris_2d[:,0],
'c2':iris_2d[:,1]
})
print(df['c1'].corr(df['c2']))


-0.10936924995064937


In [109]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
print('mean is ',iris_2d[:,2].mean())
print('median is' ,np.median(iris_2d[:,2]))
print('standard deviation is ', iris_2d[:,2].std())

mean is  3.758666666666666
median is 4.35
standard deviation is  1.7585291834055212


In [110]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints: 
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
plength=iris_2d[:,2]
slength=iris_2d[:,0]
v=(np.pi*plength*(slength**2))/3
v=v[:,np.newaxis]
np.hstack([iris_2d,v])

array([[5.10000000e+00, 3.50000000e+00, 1.40000000e+00, 2.00000000e-01,
        3.81326516e+01],
       [4.90000000e+00, 3.00000000e+00, 1.40000000e+00, 2.00000000e-01,
        3.52004985e+01],
       [4.70000000e+00, 3.20000000e+00, 1.30000000e+00, 2.00000000e-01,
        3.00723721e+01],
       [4.60000000e+00, 3.10000000e+00, 1.50000000e+00, 2.00000000e-01,
        3.32380503e+01],
       [5.00000000e+00, 3.60000000e+00, 1.40000000e+00, 2.00000000e-01,
        3.66519143e+01],
       [5.40000000e+00, 3.90000000e+00, 1.70000000e+00, 4.00000000e-01,
        5.19116770e+01],
       [4.60000000e+00, 3.40000000e+00, 1.40000000e+00, 3.00000000e-01,
        3.10221803e+01],
       [5.00000000e+00, 3.40000000e+00, 1.50000000e+00, 2.00000000e-01,
        3.92699082e+01],
       [4.40000000e+00, 2.90000000e+00, 1.40000000e+00, 2.00000000e-01,
        2.83832424e+01],
       [4.90000000e+00, 3.10000000e+00, 1.50000000e+00, 1.00000000e-01,
        3.77148198e+01],
       [5.40000000e+00, 3.7000

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [111]:
x = np.ones((4),dtype=np.int64)
print(x)

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [112]:
x=np.arange(1,10)
y=np.split(x,[4,6])
print(y)

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [113]:
x=np.random.randint(1,10,[2,5])
xmin=x.min(axis=1)
xmax=x.max(axis=1)
print(x)
print('minimun value: ',xmin)
print('maximum value: ',xmax)

[[1 9 5 9 3]
 [6 6 6 1 3]]
minimun value:  [1 1]
maximum value:  [9 6]


### Pandas

Run the following load command and solve the following questions

In [114]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [115]:
df=pd.DataFrame(iris)
print(df.nunique())

0    35
1    23
2    43
3    22
4     3
dtype: int64


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [116]:
bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5])
category = {1: 'small', 2: 'medium', 3: 'large'}
text_arr = [category[x] for x in bin]
print(text_arr)

['small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'large', 'large', 'large', 'large', 'large

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [117]:
value, counts = np.unique(iris[:, 2], return_counts=True)
print(value[np.argmax(counts)])

b'1.5'
