Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways 
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray** 



In [ ]:
import numpy as np

In [ ]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it 
import numpy as np
list = [x for x in range (1,6)]
##print (list)

arrays = np.array(list)
print (arrays)


# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it 
list = [x for x in range (10)]
##print (list)

subl = []
resultant_2Darray = []
cnt = 0 
for val in list :
  subl.append(val)
  cnt +=1
  if cnt >2 :
    resultant_2Darray.append(subl)
    subl= []
    cnt = 0

##print(resultant_2Darray)

resultant_numpyarray_2d = np.array(resultant_2Darray)
print(resultant_numpyarray_2d)

[1 2 3 4 5]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]
a = np.random.rand(3,4)
print(a)
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
b = np.zeros([3,4] , dtype = int)
print(b)
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
c = np.ones([3,4] , dtype = int)
print(c)




[[0.7413147  0.01487151 0.53639921 0.75372951]
 [0.03517242 0.1300047  0.83962339 0.37161972]
 [0.60486491 0.40565105 0.99183647 0.28018194]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
array = np.linspace(0,2,20)
print(array)

[0.         0.10526316 0.21052632 0.31578947 0.42105263 0.52631579
 0.63157895 0.73684211 0.84210526 0.94736842 1.05263158 1.15789474
 1.26315789 1.36842105 1.47368421 1.57894737 1.68421053 1.78947368
 1.89473684 2.        ]


### Basic array operations
- algebraic operations 
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])
print(a)

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]]


In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
np.add(a,b)


array([[ 7, 22, 26],
       [99, 40, 82],
       [62, 56, 80]])

In [ ]:
np.subtract(a,b)

array([[-15, -10, -10],
       [-81, -34, -80],
       [-60, -40, -70]])

In [ ]:
np.multiply(a,b)

array([[-44,  96, 144],
       [810, 111,  81],
       [ 61, 384, 375]])

In [ ]:
np.divide(a,b)

array([[-0.36363636,  0.375     ,  0.44444444],
       [ 0.1       ,  0.08108108,  0.01234568],
       [ 0.01639344,  0.16666667,  0.06666667]])

In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0 
np.sum(a,axis = 0)


array([ 6, 17, 14])

In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=1 
np.sum(a , axis =1)

array([10, 13, 14])

In [ ]:
# Write a NumPy function to reverse the array 'a' 
np.flip(a)

array([[ 5,  8,  1],
       [ 1,  3,  9],
       [ 8,  6, -4]])

In [ ]:
# Write a NumPy function to reverse the array 'a' along axis=0
np.flip(a,axis =0)

array([[ 1,  8,  5],
       [ 9,  3,  1],
       [-4,  6,  8]])

In [ ]:
# Write a NumPy function to reverse the array 'a' along axis=1
np.flip(a,axis = 1)

array([[ 8,  6, -4],
       [ 1,  3,  9],
       [ 5,  8,  1]])

### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])
print(a)

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]]


In [ ]:
# Write a NumPy function to sort the array 'a' 

# Write a NumPy function to sort the array 'a' along axis=0
np.sort(a,0)

array([[-4,  3,  1],
       [ 1,  6,  5],
       [ 9,  8,  8]])

In [ ]:
# Write a NumPy function to sort the array 'a' along axis=1
np.sort(a,1)

array([[-4,  6,  8],
       [ 1,  3,  9],
       [ 1,  5,  8]])

In [ ]:
# Write a NumPy function to sort the array 'a' in descending order along axis=0
np.sort(a,0)[::-1]

array([[ 9,  8,  8],
       [ 1,  6,  5],
       [-4,  3,  1]])

In [ ]:
# Write a NumPy function to argsort the array along axis=0
arg_sort1 = np.argsort(a,axis=0)
print(arg_sort1)
# Write a NumPy function to argsort the array along axis=1
arg_sort2 = np.argsort(a,axis = 1)
print(arg_sort2)

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [ ]:
# Write a NumPy function to argsort the array along axis=0
arg_sort1 = np.argsort(b,axis=0)
print(arg_sort1)
# Write a NumPy function to argsort the array along axis=1
arg_sort2 = np.argsort(b,axis = 1)
print(arg_sort2)

[[0 0 0]
 [2 1 2]
 [1 2 1]]
[[0 1 2]
 [1 2 0]
 [1 0 2]]


In [ ]:
 ## Write a NumPy function to concatenate the arrays 'a' and 'b'
np.concatenate((a,b))

array([[-4,  6,  8],
       [ 9,  3,  1],
       [ 1,  8,  5],
       [11, 16, 18],
       [90, 37, 81],
       [61, 48, 75]])

In [ ]:

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
np.concatenate((a,b),axis = 0)
# Note: You can do the same function using stacking, discover and try that :)


array([[-4,  6,  8],
       [ 9,  3,  1],
       [ 1,  8,  5],
       [11, 16, 18],
       [90, 37, 81],
       [61, 48, 75]])

In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 1
np.concatenate((a,b),axis = 1)

array([[-4,  6,  8, 11, 16, 18],
       [ 9,  3,  1, 90, 37, 81],
       [ 1,  8,  5, 61, 48, 75]])

### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the number of dimensions of the array  
def number_of_dimension(arr):
  
  return arr.ndim

dimension = number_of_dimension(a)
print(dimension)
# Write a NumPy function to get the Shape of the array  

# Write a NumPy function to get the Size of the array
np.size(a)

2


9

In [ ]:
np.shape(a)

(3, 3)

In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
b = np.reshape(a,(1,9))
b

array([[4, 6, 8, 9, 3, 1, 1, 8, 5]])

In [ ]:
# Write a NumPy function to add a new axis to the array 'a' 
# Note : Show atleast two different ways of doing this 
arr = a[:,np.newaxis]
print (arr)

[[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]]


In [ ]:
np.expand_dims(a, axis=1)

array([[[4, 6, 8]],

       [[9, 3, 1]],

       [[1, 8, 5]]])

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range

# indexing by a integer
print(a[0][2])

#indexing by a tuple
print(a[(0,1)])

# using range
print(a[1:])   
print(a[:2, 1:])


0
6
[[6 0]
 [8 5]]
[[0 3 1]
 [1 8 5]]
[[6 0]
 [3 1]]


In [ ]:
import numpy as np
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4 
#arr_new = lambda x: x>4
#arr_new(a)

def select_values(arr):
    return arr[arr > 4]

print(select_values(a))


[6 8 5]


In [ ]:
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
def greater_and_divisible(arr):
  condition1 = arr>4
  condition2 = arr%2==0
  ans = np.logical_and(condition1,condition2)
  return arr[ans]

greater_and_divisible(a)





array([6, 8])

### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
def increment(arr):
    arr2 = np.copy(arr) 
    arr2 += 1 
    return arr2
d = np.array(increment(a))
print(d)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset 

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
import pandas as pd
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
print(iris_2d)
df = pd.DataFrame(iris_2d,columns = ['sepallength', 'sepalwidth', 'petallength', 'petalwidth'])
print(df)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

#### Basic Data Analysis

In [ ]:
# Write a Pandas function to drop rows that contain a missing val
##df.dropna()
check_nan_rows = df.isnull().values.any()
print (check_nan_rows)

df.dropna()

False


column1  column2  column3  column4
0        5.1      3.5      1.4      0.2
1        4.9      3.0      1.4      0.2
2        4.7      3.2      1.3      0.2
3        4.6      3.1      1.5      0.2
4        5.0      3.6      1.4      0.2
..       ...      ...      ...      ...
145      6.7      3.0      5.2      2.3
146      6.3      2.5      5.0      1.9
147      6.5      3.0      5.2      2.0
148      6.2      3.4      5.4      2.3
149      5.9      3.0      5.1      1.8

[150 rows x 4 columns]

In [ ]:
# Write a Pandas function to find the correlation between the first two columns.
print(df['column1'].corr(df['column2']))


-0.10936924995064937


In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
df['column3'].mean()


3.758666666666666

In [ ]:
df['column3'].median()

4.35

In [ ]:
df['column3'].std()

1.7644204199522626

In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints: 
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
def add_volume(df):
    pi = np.pi
    vol = (pi *df['petallength'] * df['sepallength']**2)/3
    df['volume'] = vol
    
    return df


add_volume(df)



sepallength  sepalwidth  petallength  petalwidth      volume
0            5.1         3.5          1.4         0.2   38.132652
1            4.9         3.0          1.4         0.2   35.200498
2            4.7         3.2          1.3         0.2   30.072372
3            4.6         3.1          1.5         0.2   33.238050
4            5.0         3.6          1.4         0.2   36.651914
..           ...         ...          ...         ...         ...
145          6.7         3.0          5.2         2.3  244.445230
146          6.3         2.5          5.0         1.9  207.816354
147          6.5         3.0          5.2         2.0  230.069302
148          6.2         3.4          5.4         2.3  217.373079
149          5.9         3.0          5.1         1.8  185.910028

[150 rows x 5 columns]

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
y =np. ones(4,dtype = np.int64)
print(y)
x = np.arange(4, dtype=np.int64)
print (x)

[1 1 1 1]
[0 1 2 3]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
arr = [1,2,3,4,5,6,7,8,9]
arr1 = np.split(arr,[4,6])
print(arr1)


[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
import numpy as np
x = np.random.randint(low=0, high=10, size=(2, 5))
max_val = np.amax(x, axis=1)
max_idx = np.argmax(x, axis=1)
min_val = np.amin(x, axis=1)
min_idx = np.argmin(x, axis=1)
print( max_val)
print( max_idx)
print(min_val)
print( min_idx)

[8 8]
[4 0]
[2 2]
[1 2]


### Pandas

Run the following load command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
df = pd.DataFrame(iris,columns = ['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'])
df

sepallength sepalwidth petallength petalwidth            species
0        b'5.1'     b'3.5'      b'1.4'     b'0.2'     b'Iris-setosa'
1        b'4.9'     b'3.0'      b'1.4'     b'0.2'     b'Iris-setosa'
2        b'4.7'     b'3.2'      b'1.3'     b'0.2'     b'Iris-setosa'
3        b'4.6'     b'3.1'      b'1.5'     b'0.2'     b'Iris-setosa'
4        b'5.0'     b'3.6'      b'1.4'     b'0.2'     b'Iris-setosa'
..          ...        ...         ...        ...                ...
145      b'6.7'     b'3.0'      b'5.2'     b'2.3'  b'Iris-virginica'
146      b'6.3'     b'2.5'      b'5.0'     b'1.9'  b'Iris-virginica'
147      b'6.5'     b'3.0'      b'5.2'     b'2.0'  b'Iris-virginica'
148      b'6.2'     b'3.4'      b'5.4'     b'2.3'  b'Iris-virginica'
149      b'5.9'     b'3.0'      b'5.1'     b'1.8'  b'Iris-virginica'

[150 rows x 5 columns]

Q4 Write a Pandas function to find the count of unique species.

In [ ]:
df['species'].value_counts()

b'Iris-setosa'        50
b'Iris-versicolor'    50
b'Iris-virginica'     50
Name: species, dtype: int64

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
df['petallength'].mode()

0    b'1.5'
Name: petallength, dtype: object

In [ ]:
import pandas as pd

def length(df):
    bins = [0.0, 3.0, 5.0, 7.0]
    labels = ['small', 'medium', 'large']
    df['petal_length_bin'] = pd.cut(df['petal_length'], bins=bins, labels=labels)
    return df['petal_length_bin'].values

import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])
iris_2d = pd.DataFrame(iris, columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])
petal_length =length(iris_2d)
print(petal_length)

['small', 'small', 'small', 'small', 'small', ..., 'large', 'medium', 'large', 'large', 'large']
Length: 150
Categories (3, object): ['small' < 'medium' < 'large']


In [ ]:
df['petallength'].max() ## to get max possible value of petal length to decide bins

b'6.9'