Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways 
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray** 



In [ ]:
import numpy as np

In [ ]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it 
a = list[1,2,3,4,5]
print(a)


# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it 
b = list[[1,2,3],[4,5,6],[7,8,9]]
print(b)

list[1, 2, 3, 4, 5]
list[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]
import numpy as np
from numpy import random
a= random.randint(100, size=(3,4))
print(a, "\n")

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
b=np.zeros((3,4))
print(b,"\n")

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
c = np.ones((3,4))
print(c)


[[80 44 67 18]
 [11 23 77 31]
 [23 92  1 44]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
a = np.arange(1,100,2)
print(a)
# Hint : Use np.arange or np.linspace

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


### Basic array operations
- algebraic operations 
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])
import numpy as np


print(np.add(a,b),"\n")
print(np.subtract(a,b),"\n")
print(np.multiply(a,b), "\n")
print(np.divide(a,b),"\n")


[[ 7 22 26]
 [99 40 82]
 [62 56 80]] 

[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]] 

[[-44  96 144]
 [810 111  81]
 [ 61 384 375]] 

[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]] 



In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0 
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.sum(a,axis =0)
print(b,"\n")

# Write a NumPy function to get the sum of the array 'a' along axis=1 
c= np.sum(a,axis=1)
print(c)


[ 6 17 14] 

[10 13 14]


In [ ]:
# Write a NumPy function to reverse the array 'a' 
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
print(np.flip(a),"\n")





# Write a NumPy function to reverse the array 'a' along axis=0
print(np.flip(a,0),"\n")

# Write a NumPy function to reverse the array 'a' along axis=1
print(np.flip(a,1),"\n")


[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]] 

[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]] 

[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]] 



### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a' 
print(np.sort(a,axis = None),"\n")

# Write a NumPy function to sort the array 'a' along axis=0
print(np.sort(a,0),"\n")

# Write a NumPy function to sort the array 'a' along axis=1
print(np.sort(a,1),"\n")

# Write a NumPy function to sort the array 'a' in descending order along axis=0





[-4  1  1  3  5  6  8  8  9] 

[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]] 

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]] 



TypeError: ignored

In [ ]:
# Write a NumPy function to argsort the array along axis=0
print(np.argsort(a, axis =0),"\n")

# Write a NumPy function to argsort the array along axis=1


[[0 1 1]
 [2 0 2]
 [1 2 0]]


In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])
print(np.concatenate((a,b),axis = None),"\n")

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
print(np.concatenate((a,b),axis = 0))

# Note: You can do the same function using stacking, discover and try that :)


[-4  6  8  9  3  1  1  8  5 11 16 18 90 37 81 61 48 75] 

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
print(a.ndim)

# Write a NumPy function to get the Shape of the array  

print(a.shape)
# Write a NumPy function to get the Size of the array
print(a.size)



2
(3, 3)
9


In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])
print(a.reshape(1,9))


[[4 6 8 9 3 1 1 8 5]]


In [ ]:
# Write a NumPy function to add a new axis to the array 'a' 
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])
print(a.reshape(3,1,3))
# Note : Show atleast two different ways of doing this 



[[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range


In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4 
import numpy as np
a = np.array([[4,6,5], [0, 3, 1], [1, 8, 5]])

for i in a:
  for j in i:
    if(j>4 ):
      print(j, end=" ")

print("\n")
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
for i in a:
  for j in i:
    if(j>4 and j%2==0):
      print(j, end=" ")



6 5 8 5 

6 8 

### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
b = np.copy(a)
print(b+1)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset 

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [ ]:
# Write a Pandas function to drop rows that contain a missing value. 
import pandas as pd
df = pd.read_csv( 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')
new_df = df.dropna()
print(new_df.to_string(index = False,header = False) )



4.9 3.0 1.4 0.2     Iris-setosa
4.7 3.2 1.3 0.2     Iris-setosa
4.6 3.1 1.5 0.2     Iris-setosa
5.0 3.6 1.4 0.2     Iris-setosa
5.4 3.9 1.7 0.4     Iris-setosa
4.6 3.4 1.4 0.3     Iris-setosa
5.0 3.4 1.5 0.2     Iris-setosa
4.4 2.9 1.4 0.2     Iris-setosa
4.9 3.1 1.5 0.1     Iris-setosa
5.4 3.7 1.5 0.2     Iris-setosa
4.8 3.4 1.6 0.2     Iris-setosa
4.8 3.0 1.4 0.1     Iris-setosa
4.3 3.0 1.1 0.1     Iris-setosa
5.8 4.0 1.2 0.2     Iris-setosa
5.7 4.4 1.5 0.4     Iris-setosa
5.4 3.9 1.3 0.4     Iris-setosa
5.1 3.5 1.4 0.3     Iris-setosa
5.7 3.8 1.7 0.3     Iris-setosa
5.1 3.8 1.5 0.3     Iris-setosa
5.4 3.4 1.7 0.2     Iris-setosa
5.1 3.7 1.5 0.4     Iris-setosa
4.6 3.6 1.0 0.2     Iris-setosa
5.1 3.3 1.7 0.5     Iris-setosa
4.8 3.4 1.9 0.2     Iris-setosa
5.0 3.0 1.6 0.2     Iris-setosa
5.0 3.4 1.6 0.4     Iris-setosa
5.2 3.5 1.5 0.2     Iris-setosa
5.2 3.4 1.4 0.2     Iris-setosa
4.7 3.2 1.6 0.2     Iris-setosa
4.8 3.1 1.6 0.2     Iris-setosa
5.4 3.4 1.5 0.4     Iris-setosa
5.2 4.1 

In [ ]:
# Write a Pandas function to find the correlation between the first two columns.
d = df.iloc[:, 0].corr(df.iloc[:, 1])
print(d)



-0.10378414795681824


In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column3
a = df.iloc[:,2].mean()
b = df.iloc[:,2].median()
c = df.iloc[:,2].std()
print(a,'\n',b,'\n',c)

3.774496644295302 
 4.4 
 1.7596511617753423


InvalidIndexError: ignored

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
a = np.ones((1,4))
print(a)

[[1. 1. 1. 1.]]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
import numpy as np
x = np.arange(1,10, dtype = np.int64)
a = np.split(x,[4,6])
print(a)


[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
from numpy import random as rd
a=np.random.randint(10,size=(2,5))
print(a)

print("Max value is  ", np.max(a)," on indices", np.where(a == np.max(a))[0])
print("Min value is  ", np.min(a)," on indices",np.where(a == np.min(a))[0])





[[4 0 0 5 7]
 [6 0 3 8 1]]
Max value is   8  on index [1]
Min value is   0  on index [0 0 1]


### Pandas

Run the following load command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [ ]:
import pandas as pd

def countunique(df):
  a = df['species'].unique()
  print(len(a))

df = pd.read_csv( 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')
df.columns=['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species']
countunique(df)


3


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [ ]:
def bining(df):
  l=[]
  for a in df["petallength"]:
    if a<3:
      l.append("small")
    elif a>=3 and a<=5 :
      l.append("medium")
    else:
      l.append("large") 
  print(l)


df = pd.read_csv( 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')
df.columns=['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species']
bining(df)

['small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'large', 'large', 'large', 'large', 'large', 'medi

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
import pandas as pd

def mostfreq(df):
  a=df.mode()
  print(a["petallength"][0])

df = pd.read_csv( 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')
df.columns=['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species']
mostfreq(df)

1.5
